### ISSUE TITLE
Button Cleanup Conversation

### ISSUE THREAD

**Issue by mdchristians** [Hireology/molecules#15]
Let's talk some changes with the Button component.

**Switch the component to use a `PureComponent`.**
In react 15 it'll be re-rendered whenever it's parent is re-rendered. We can solve this by making it a PureComponent.

**Add an `isLoading` prop.** 
So we can stay consistent with both loading icon in the button as well as the spacing between it and the loading text.

**Add an `icon` prop.** 
So we can stay consistent with both icon in the button as well as the spacing between it and the text. I would imagine the icon would just take a font-awesome component.

**General (Not fixes, just curious)**

- Do we need `onMouseDown` and `onClick`?
- Why `onMouseOver` over `onMouseEnter`?
- Why `onMouseOut` over `onMouseLeave`?

For the sake of consistency,

**Comment by mariadoesmath** [comment]
I'm going to separate the PureComponent work into it's own issue. We should probably make everything a pure component if that's the case.

**Comment by megancoyle** [comment]
Closing this out since we're tracking any Molecules work via Jira
