### ISSUE TITLE
PR Checks Cleanup

### ISSUE THREAD

**Issue by mdchristians** [Hireology/molecules#41]
Let's go through and remove, or just hide, some of the PR checks that we really don't care about.  I think the main ones we really need to see and care about are:

1. continuous-integration/travis-ci/pr
2. netlify/hireology-storybook/deploy-preview

![Screen Shot 2020-05-01 at 9 27 38 AM](https://user-images.githubusercontent.com/4482233/80812845-6091b480-8b8e-11ea-81df-06615f9f397d.png)

**Comment by megancoyle** [comment]
Closing this out since we're tracking any Molecules work via Jira
