### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by mdchristians** [Hireology/molecules#42]
Let's start incorporating a changelog (`CHANGELOG.md`) to show differences in releases. Here's a good reference for info for the what/why/who - [KeepAChangelog.com](https://keepachangelog.com/en/1.0.0/)

We can [automate this if you'd like or manually update it](https://depfu.com/blog/changelogs-to-write-or-to-generate).  Automation looks to use commit messages, so we'd have to standardize a way we wrote commit messages for Molecules.

For automation, checkout:

- [auto-changelog](https://www.npmjs.com/package/auto-changelog)
- [standard-version](https://github.com/conventional-changelog/standard-version) - [more info](https://medium.com/jobtome-engineering/how-to-generate-changelog-using-conventional-commits-10be40f5826c)

**Comment by megancoyle** [comment]
Closing this out since we're tracking any Molecules work via Jira
